---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: highscore
  namespace: j4sysiak-dev
  labels:
    app: highscore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highscore
  template:
    metadata:
      labels:
        app: highscore
    spec:
      containers:
        - name: highscore
          # To jest obraz, który OpenShift zbudował dla Ciebie z GitHuba
          image: image-registry.openshift-image-registry.svc:5000/j4sysiak-dev/highscore:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: highscore
  namespace: j4sysiak-dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: highscore
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: highscore
  namespace: j4sysiak-dev
  labels:
    app: highscore
spec:
  # Twoja unikalna domena z Sandboxa
  host: platform-j4sysiak-dev.apps.rm3.7wse.p1.openshiftapps.com
  path: /highscore
  to:
    kind: Service
    name: highscore
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect